[Variables]
CpuUsage-SensorId=0xf0000300
CpuUsage-SensorInstance=0x0
CpuUsage-EntryId=0x700000d
CpuTemperature-SensorId=0xf7067980
CpuTemperature-SensorInstance=0x0
CpuTemperature-EntryId=0x1000007
GpuUsage-SensorId=0xe0002000
GpuUsage-SensorInstance=0x0
GpuUsage-EntryId=0x7000000
GpuTemperature-SensorId=0xe0002000
GpuTemperature-SensorInstance=0x0
GpuTemperature-EntryId=0x1000000
VramUsage-SensorId=0xe0002000
VramUsage-SensorInstance=0x0
VramUsage-EntryId=0x7000008

; SMV CONFIG

[HWiNFO-Config-CPU]
CpuUsage = CPU Usage (%)
CpuTemperature = CPU Temperature (degrees)

[HWiNFO-Config-GPU]
GpuUsage = GPU Usage (%)
GpuTemperature = GPU Temperature (degrees)
VramUsage = VRAM Usage (%)
